apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluence
  template:
    metadata:
      labels:
        app: confluence
    spec:
      containers:
      - name: confluence-container
        image: 29trxngxx/confluence:v1
        ports:
        - containerPort: 8090
        env:
        - name: TZ
          value: "Asia/Ho_Chi_Minh"
        volumeMounts:
        - name: home-data
          mountPath: /var/confluence
      volumes:
      - name: home-data
        persistentVolumeClaim:
          claimName: home-data
