apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/confluence-network-bridge: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_bin
            - --transaction-isolation=READ-COMMITTED
            - --innodb_log_file_size=256M
            - --max_allowed_packet=256M
            - --log_bin_trust_function_creators=1
          env:
            - name: MYSQL_DATABASE
              value: confluence
            - name: MYSQL_PASSWORD
              value: 'seta@123'
            - name: MYSQL_ROOT_PASSWORD
              value: 'seta@123'
            - name: MYSQL_USER
              value: confluence
            - name: TZ
              value: Asia/Ho_Chi_Minh
          image: mysql:8.0
          name: mysql-confluence
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
