apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-confluence
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: confluence
        - name: MYSQL_PASSWORD
          value: 'seta@123'
        - name: MYSQL_ROOT_PASSWORD
          value: 'seta@123'
        - name: MYSQL_USER
          value: confluence
        - name: TZ
          value: Asia/Ho_Chi_Minh
        args:
          - mysqld
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_bin
          - --transaction-isolation=READ-COMMITTED
          - --innodb_log_file_size=256M
          - --max_allowed_packet=256M
          - --log_bin_trust_function_creators=1
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      restartPolicy: Always
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
